// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/auctionServer/auction.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckTypes int32

const (
	AckTypes_FAIL      AckTypes = 0
	AckTypes_SUCCESS   AckTypes = 1
	AckTypes_EXCEPTION AckTypes = 2
)

// Enum value maps for AckTypes.
var (
	AckTypes_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "EXCEPTION",
	}
	AckTypes_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"EXCEPTION": 2,
	}
)

func (x AckTypes) Enum() *AckTypes {
	p := new(AckTypes)
	*p = x
	return p
}

func (x AckTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auctionServer_auction_proto_enumTypes[0].Descriptor()
}

func (AckTypes) Type() protoreflect.EnumType {
	return &file_grpc_auctionServer_auction_proto_enumTypes[0]
}

func (x AckTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckTypes.Descriptor instead.
func (AckTypes) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auctionServer_auction_proto_rawDescGZIP(), []int{0}
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"` //Client id
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`      //Logical Lamport clock
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`    //Bid amount
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_grpc_auctionServer_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionServer_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_grpc_auctionServer_auction_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Amount) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *Amount) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"` //Logical Lamport clock
	Ack           AckTypes               `protobuf:"varint,3,opt,name=ack,proto3,enum=main.AckTypes" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_grpc_auctionServer_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionServer_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_grpc_auctionServer_auction_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *Ack) GetAck() AckTypes {
	if x != nil {
		return x.Ack
	}
	return AckTypes_FAIL
}

type AuctionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`   //Logical Lamport clock
	Result        int32                  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"` // If the auction is over, returns the result; otherwise returns the highest current bid
	IsOver        bool                   `protobuf:"varint,4,opt,name=isOver,proto3" json:"isOver,omitempty"` //Is the auction over/done?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionResult) Reset() {
	*x = AuctionResult{}
	mi := &file_grpc_auctionServer_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionResult) ProtoMessage() {}

func (x *AuctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionServer_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionResult.ProtoReflect.Descriptor instead.
func (*AuctionResult) Descriptor() ([]byte, []int) {
	return file_grpc_auctionServer_auction_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionResult) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *AuctionResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *AuctionResult) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

var File_grpc_auctionServer_auction_proto protoreflect.FileDescriptor

const file_grpc_auctionServer_auction_proto_rawDesc = "" +
	"\n" +
	" grpc/auctionServer/auction.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"R\n" +
	"\x06Amount\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\">\n" +
	"\x03Ack\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock\x12!\n" +
	"\x03ack\x18\x03 \x01(\x0e2\x0f.main.Ack_typesR\x03ack\"U\n" +
	"\rAuctionResult\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x05R\x06result\x12\x16\n" +
	"\x06isOver\x18\x04 \x01(\bR\x06isOver*1\n" +
	"\tAck_types\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x022`\n" +
	"\aAuction\x12\x1e\n" +
	"\x03Bid\x12\f.main.Amount\x1a\t.main.Ack\x125\n" +
	"\x06Result\x12\x16.google.protobuf.Empty\x1a\x13.main.AuctionResultB\x03Z\x01.b\x06proto3"

var (
	file_grpc_auctionServer_auction_proto_rawDescOnce sync.Once
	file_grpc_auctionServer_auction_proto_rawDescData []byte
)

func file_grpc_auctionServer_auction_proto_rawDescGZIP() []byte {
	file_grpc_auctionServer_auction_proto_rawDescOnce.Do(func() {
		file_grpc_auctionServer_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auctionServer_auction_proto_rawDesc), len(file_grpc_auctionServer_auction_proto_rawDesc)))
	})
	return file_grpc_auctionServer_auction_proto_rawDescData
}

var file_grpc_auctionServer_auction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_auctionServer_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_auctionServer_auction_proto_goTypes = []any{
	(AckTypes)(0),         // 0: main.Ack_types
	(*Amount)(nil),        // 1: main.Amount
	(*Ack)(nil),           // 2: main.Ack
	(*AuctionResult)(nil), // 3: main.AuctionResult
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_grpc_auctionServer_auction_proto_depIdxs = []int32{
	0, // 0: main.Ack.ack:type_name -> main.Ack_types
	1, // 1: main.Auction.Bid:input_type -> main.Amount
	4, // 2: main.Auction.Result:input_type -> google.protobuf.Empty
	2, // 3: main.Auction.Bid:output_type -> main.Ack
	3, // 4: main.Auction.Result:output_type -> main.AuctionResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_auctionServer_auction_proto_init() }
func file_grpc_auctionServer_auction_proto_init() {
	if File_grpc_auctionServer_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auctionServer_auction_proto_rawDesc), len(file_grpc_auctionServer_auction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auctionServer_auction_proto_goTypes,
		DependencyIndexes: file_grpc_auctionServer_auction_proto_depIdxs,
		EnumInfos:         file_grpc_auctionServer_auction_proto_enumTypes,
		MessageInfos:      file_grpc_auctionServer_auction_proto_msgTypes,
	}.Build()
	File_grpc_auctionServer_auction_proto = out.File
	file_grpc_auctionServer_auction_proto_goTypes = nil
	file_grpc_auctionServer_auction_proto_depIdxs = nil
}
