// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/backend/backend.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_grpc_backend_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_backend_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_grpc_backend_backend_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Answer) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_grpc_backend_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_backend_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_grpc_backend_backend_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

var File_grpc_backend_backend_proto protoreflect.FileDescriptor

const file_grpc_backend_backend_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc/backend/backend.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\x1a grpc/auctionServer/auction.proto\".\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock\"/\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock2\xb0\x01\n" +
	"\aBackend\x12)\n" +
	"\x0eTryToUpdateBid\x12\f.main.Amount\x1a\t.main.Ack\x12'\n" +
	"\bElection\x12\r.main.Message\x1a\f.main.Answer\x12#\n" +
	"\aVictory\x12\r.main.Message\x1a\t.main.Ack\x12,\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\f.main.AnswerB\x03Z\x01.b\x06proto3"

var (
	file_grpc_backend_backend_proto_rawDescOnce sync.Once
	file_grpc_backend_backend_proto_rawDescData []byte
)

func file_grpc_backend_backend_proto_rawDescGZIP() []byte {
	file_grpc_backend_backend_proto_rawDescOnce.Do(func() {
		file_grpc_backend_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_backend_backend_proto_rawDesc), len(file_grpc_backend_backend_proto_rawDesc)))
	})
	return file_grpc_backend_backend_proto_rawDescData
}

var file_grpc_backend_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_backend_backend_proto_goTypes = []any{
	(*Answer)(nil),        // 0: main.Answer
	(*Message)(nil),       // 1: main.Message
	(*Amount)(nil),        // 2: main.Amount
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
	(*Ack)(nil),           // 4: main.Ack
}
var file_grpc_backend_backend_proto_depIdxs = []int32{
	2, // 0: main.Backend.TryToUpdateBid:input_type -> main.Amount
	1, // 1: main.Backend.Election:input_type -> main.Message
	1, // 2: main.Backend.Victory:input_type -> main.Message
	3, // 3: main.Backend.Ping:input_type -> google.protobuf.Empty
	4, // 4: main.Backend.TryToUpdateBid:output_type -> main.Ack
	0, // 5: main.Backend.Election:output_type -> main.Answer
	4, // 6: main.Backend.Victory:output_type -> main.Ack
	0, // 7: main.Backend.Ping:output_type -> main.Answer
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_backend_backend_proto_init() }
func file_grpc_backend_backend_proto_init() {
	if File_grpc_backend_backend_proto != nil {
		return
	}
	file_grpc_auctionServer_auction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_backend_backend_proto_rawDesc), len(file_grpc_backend_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_backend_backend_proto_goTypes,
		DependencyIndexes: file_grpc_backend_backend_proto_depIdxs,
		MessageInfos:      file_grpc_backend_backend_proto_msgTypes,
	}.Build()
	File_grpc_backend_backend_proto = out.File
	file_grpc_backend_backend_proto_goTypes = nil
	file_grpc_backend_backend_proto_depIdxs = nil
}
