// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: backend/backend.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckTypes int32

const (
	AckTypes_FAIL      AckTypes = 0
	AckTypes_SUCCESS   AckTypes = 1
	AckTypes_EXCEPTION AckTypes = 2
	AckTypes_OK        AckTypes = 3
)

// Enum value maps for AckTypes.
var (
	AckTypes_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "EXCEPTION",
		3: "OK",
	}
	AckTypes_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"EXCEPTION": 2,
		"OK":        3,
	}
)

func (x AckTypes) Enum() *AckTypes {
	p := new(AckTypes)
	*p = x
	return p
}

func (x AckTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_backend_proto_enumTypes[0].Descriptor()
}

func (AckTypes) Type() protoreflect.EnumType {
	return &file_backend_backend_proto_enumTypes[0]
}

func (x AckTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckTypes.Descriptor instead.
func (AckTypes) EnumDescriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{0}
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`   //Logical Lamport clock
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` //Bid amount
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_backend_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *Amount) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"` //Logical Lamport clock
	Ack           AckTypes               `protobuf:"varint,3,opt,name=ack,proto3,enum=AckTypes" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_backend_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

func (x *Ack) GetAck() AckTypes {
	if x != nil {
		return x.Ack
	}
	return AckTypes_FAIL
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_backend_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{2}
}

func (x *Answer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Answer) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

type VictoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Clock         int32                  `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VictoryMessage) Reset() {
	*x = VictoryMessage{}
	mi := &file_backend_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VictoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VictoryMessage) ProtoMessage() {}

func (x *VictoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VictoryMessage.ProtoReflect.Descriptor instead.
func (*VictoryMessage) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{3}
}

func (x *VictoryMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VictoryMessage) GetClock() int32 {
	if x != nil {
		return x.Clock
	}
	return 0
}

var File_backend_backend_proto protoreflect.FileDescriptor

const file_backend_backend_proto_rawDesc = "" +
	"\n" +
	"\x15backend/backend.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\x06Amount\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"9\n" +
	"\x03Ack\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock\x12\x1c\n" +
	"\x03ack\x18\x03 \x01(\x0e2\n" +
	".Ack_typesR\x03ack\".\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock\"6\n" +
	"\x0eVictoryMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05clock\x18\x02 \x01(\x05R\x05clock*9\n" +
	"\tAck_types\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x02\x12\x06\n" +
	"\x02OK\x10\x032y\n" +
	"\aBackend\x12\x1f\n" +
	"\x0eTryToUpdateBid\x12\a.Amount\x1a\x04.Ack\x12+\n" +
	"\bElection\x12\x16.google.protobuf.Empty\x1a\a.Answer\x12 \n" +
	"\aVictory\x12\x0f.VictoryMessage\x1a\x04.AckB\x03Z\x01.b\x06proto3"

var (
	file_backend_backend_proto_rawDescOnce sync.Once
	file_backend_backend_proto_rawDescData []byte
)

func file_backend_backend_proto_rawDescGZIP() []byte {
	file_backend_backend_proto_rawDescOnce.Do(func() {
		file_backend_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_backend_proto_rawDesc), len(file_backend_backend_proto_rawDesc)))
	})
	return file_backend_backend_proto_rawDescData
}

var file_backend_backend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_backend_backend_proto_goTypes = []any{
	(AckTypes)(0),          // 0: Ack_types
	(*Amount)(nil),         // 1: Amount
	(*Ack)(nil),            // 2: Ack
	(*Answer)(nil),         // 3: Answer
	(*VictoryMessage)(nil), // 4: VictoryMessage
	(*emptypb.Empty)(nil),  // 5: google.protobuf.Empty
}
var file_backend_backend_proto_depIdxs = []int32{
	0, // 0: Ack.ack:type_name -> Ack_types
	1, // 1: Backend.TryToUpdateBid:input_type -> Amount
	5, // 2: Backend.Election:input_type -> google.protobuf.Empty
	4, // 3: Backend.Victory:input_type -> VictoryMessage
	2, // 4: Backend.TryToUpdateBid:output_type -> Ack
	3, // 5: Backend.Election:output_type -> Answer
	2, // 6: Backend.Victory:output_type -> Ack
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_backend_backend_proto_init() }
func file_backend_backend_proto_init() {
	if File_backend_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_backend_proto_rawDesc), len(file_backend_backend_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_backend_proto_goTypes,
		DependencyIndexes: file_backend_backend_proto_depIdxs,
		EnumInfos:         file_backend_backend_proto_enumTypes,
		MessageInfos:      file_backend_backend_proto_msgTypes,
	}.Build()
	File_backend_backend_proto = out.File
	file_backend_backend_proto_goTypes = nil
	file_backend_backend_proto_depIdxs = nil
}
